# Generated by Django 6.0.3 on 2026-04-02 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=50, unique=True)),
                ('audio_file', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('escalated', 'Escalated'), ('abandoned', 'Abandoned')], default='completed', max_length=20)),
                ('called_at', models.DateTimeField()),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='calls.caller')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
    ]
