# Generated by Django 6.0.3 on 2026-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller_type',
            field=models.CharField(choices=[('new_client', 'New Client'), ('existing_client', 'Existing Client'), ('opposing_party', 'Opposing Party'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
