# Generated by Django 6.0.3 on 2026-04-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_caller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='follow_up_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='urgent_reason',
            field=models.TextField(blank=True),
        ),
    ]
