# Generated by Django 6.0.3 on 2026-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_follow_up_sent_call_urgent_call_urgent_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='requires_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
