# Generated by Django 6.0.3 on 2026-04-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_requires_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='status',
        ),
        migrations.AddField(
            model_name='call',
            name='requires_appointment_reason',
            field=models.TextField(blank=True),
        ),
    ]
