# Generated by Django 6.0.3 on 2026-04-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_remove_call_status_call_requires_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='requires_appointment_reason',
        ),
    ]
