# Generated by Django 6.0.3 on 2026-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_remove_call_requires_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='proposed_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
